/* Liste canonique des lieux de la Citadelle Chrysaldus.
   Source : la liste du MJ (onglet « Rooms by the hour » + dortoirs).
   Utilisee par le serveur ET par le cockpit : c'est le seul endroit a modifier
   pour ajouter, renommer ou retirer une salle. L'ordre ci-dessous est l'ordre
   d'affichage (menu deroulant et tableau « Lieux occupes »). */
const M1_LOCATIONS = [
  { id: "0 Arrival area",        etage: "RDC" },
  { id: "0 Main hall",           etage: "RDC" },
  { id: "0 Mr Jacques office",   etage: "RDC" },
  { id: "0' Mr Jacques studio",  etage: "RDC" },
  { id: "0 Storage",             etage: "RDC" },
  { id: "0 Arena",               etage: "RDC" },
  { id: "0 Theater",             etage: "RDC" },
  { id: "0 Foyer",               etage: "RDC" },
  { id: "0 Gymnasium",           etage: "RDC" },
  { id: "0 Staircase",           etage: "RDC" },
  { id: "1 Stairecase",          etage: "1er" },
  { id: "1 Corridor",            etage: "1er" },
  { id: "1 Dorms A (Hayeva Esteban Markel Norvodavius Askii)", etage: "1er" },
  { id: "1 Dorms B (Carnage Balerion Framschtak, Pryah, Müne)", etage: "1er" },
  { id: "1 Dorms C (Citello Nerasho Bardik)", etage: "1er" },
  { id: "1 Dorms D (Doulahex, Paxel, Gasper)", etage: "1er" },
  { id: "1 Library",             etage: "1er" },
  { id: "1' Library 1st floor",  etage: "1er" },
  { id: "1 Chill Zone",          etage: "1er" },
  { id: "2 Staircase",           etage: "2e" },
  { id: "2 Corridor",            etage: "2e" },
  { id: "2 Classroom",           etage: "2e" },
  { id: "2 Workshop room",       etage: "2e" },
  { id: "2 Armory",              etage: "2e" },
  { id: "2 Greenhouse",          etage: "2e" },
  { id: "2 Alchemy Lab",         etage: "2e" },
  { id: "2' Alchemy lab mezzanine (Myst's room)", etage: "2e" },
  { id: "3 Staircase",           etage: "3e" },
  { id: "3 Corridor",            etage: "3e" },
  { id: "3 Banquet room",        etage: "3e" },
  { id: "3 Guest House",         etage: "3e" },
  { id: "3 The Great Balcony",   etage: "3e" },
  { id: "3 Kitchens",            etage: "3e" },
  { id: "4 Staircase",           etage: "4e" },
  { id: "4 Corridor",            etage: "4e" },
  { id: "4 Eve's office",        etage: "4e" },
  { id: "4' Eve's studio",       etage: "4e" },
  { id: "4 Orb's room",          etage: "4e" },
  { id: "4' Orb's labyrinth",    etage: "4e" },
  { id: "4 Monitoring room",     etage: "4e" },
  { id: "4' Secret Elevator",    etage: "4e" },
  { id: "5 Staircase",           etage: "5e" },
  { id: "5 Corridor",            etage: "5e" },
  { id: "5 Aesteria's lab",      etage: "5e" },
  { id: "5' Secret Elevator",    etage: "5e" },
  { id: "5 Recollection Room",   etage: "5e" },
  { id: "6 Staircase",           etage: "6e" },
  { id: "6 Maevis' office",      etage: "6e" },
  { id: "6' Maevis' Suite",      etage: "6e" },
  { id: "7 Aesterias office",    etage: "7e" },
  { id: "7' Aesterias balcony",  etage: "7e" },
  { id: "7' Secret Elevator",    etage: "7e" },
  { id: "X In transit",          etage: "⇅" },
];
if (typeof module !== 'undefined' && module.exports) module.exports = { M1_LOCATIONS };
